name: transit-env2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - ipykernel
  - pip
  - pip:
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - click-plugins==1.1.1
      - cligj==0.7.2
      - configargparse==1.7
      - filelock==3.16.1
      - fiona==1.10.1
      - geojson==3.1.0
      - geopandas==1.0.1
      - idna==3.10
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - pathlib==1.0.1
      - psutil==6.1.0
      - pyogrio==0.10.0
      - pyproj==3.6.1
      - requests==2.32.3
      - shapely==2.0.6
      - urllib3==2.2.3